name: Hello Datadog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hello-datadog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print hello datadog
        run: echo "Hello Datadog"
